FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    check \
    libsubunit-dev \
    locales \
    && locale-gen en_US.UTF-8 \
    && apt-get clean
ENV LANGUAGE=en_US.UTF-8
WORKDIR /s21_string
COPY . .
CMD ["make", "test"]
